forbole/big-dipper-2.0-solana

CHANGELOG.md, src/graphql/block_time.graphql, src/graphql/types.tsx, src/screens/home/components/data_blocks/__snapshots__/index.test.tsx.snap, src/screens/home/components/data_blocks/hooks.ts, src/screens/home/components/data_blocks/index.test.tsx
=> add: average slot time

CHANGELOG.md, public/locales/en/transactions.json, src/components/single_transaction_mobile/index.tsx, src/components/transactions_list/components/mobile/index.tsx, src/graphql/transactions.graphql, src/graphql/types.tsx, src/screens/home/components/transactions/__snapshots__/index.test.tsx.snap, src/screens/home/components/transactions/components/desktop/__snapshots__/index.test.tsx.snap, src/screens/home/components/transactions/components/desktop/index.test.tsx, src/screens/home/components/transactions/components/desktop/index.tsx, src/screens/home/components/transactions/components/desktop/utils.ts, src/screens/home/components/transactions/components/mobile/__snapshots__/index.test.tsx.snap, src/screens/home/components/transactions/components/mobile/index.test.tsx, src/screens/home/components/transactions/components/mobile/index.tsx, src/screens/home/components/transactions/hooks.tsx, src/screens/home/components/transactions/index.test.tsx, src/screens/home/components/transactions/types.ts
=> add: latest transaction

src/components/avatar_name/index.tsx, src/components/name/index.tsx, src/utils/go_to_page.ts
=> update all addresses to go to address details

CHANGELOG.md, public/locales/en/blocks.json, src/graphql/block_details.graphql, src/graphql/desmos_profile.ts, src/graphql/transactions.graphql, src/graphql/types.tsx, src/screens/block_details/__snapshots__/index.test.tsx.snap, src/screens/block_details/components/overview/__snapshots__/index.test.tsx.snap, src/screens/block_details/components/overview/index.tsx, src/screens/block_details/hooks.tsx, src/screens/block_details/index.test.tsx, src/screens/block_details/types.ts, src/screens/home/components/blocks/components/desktop/__snapshots__/index.test.tsx.snap, src/screens/home/components/blocks/components/desktop/index.test.tsx, src/screens/home/components/blocks/components/desktop/index.tsx, src/screens/home/components/blocks/components/desktop/utils.ts, src/screens/home/components/blocks/components/mobile/index.test.tsx, src/screens/home/components/blocks/components/mobile/index.tsx, src/screens/home/components/blocks/hooks.tsx, src/screens/home/components/blocks/index.tsx, src/screens/home/components/blocks/types.ts
=> merge: block details with hasura

CHANGELOG.md, src/graphql/transaction_details.graphql, src/graphql/types.tsx, src/screens/transaction_details/__snapshots__/index.test.tsx.snap, src/screens/transaction_details/components/overview/__snapshots__/index.test.tsx.snap, src/screens/transaction_details/components/overview/index.test.tsx, src/screens/transaction_details/components/overview/index.tsx, src/screens/transaction_details/hooks.ts, src/screens/transaction_details/index.test.tsx, src/screens/transaction_details/types.ts
=> wip: connecting data

src/components/single_block_mobile/__snapshots__/index.test.tsx.snap, src/components/single_block_mobile/index.test.tsx, src/components/single_block_mobile/index.tsx, src/components/transactions_list_details/components/list/components/single_transaction/__snapshots__/index.test.tsx.snap, src/components/transactions_list_details/components/list/components/single_transaction/index.test.tsx, src/screens/account_details/components/transactions/__snapshots__/index.test.tsx.snap, src/screens/account_details/components/transactions/index.test.tsx, src/screens/block_details/components/overview/__snapshots__/index.test.tsx.snap, src/screens/block_details/components/overview/index.test.tsx, src/screens/block_details/components/transactions/__snapshots__/index.test.tsx.snap, src/screens/block_details/components/transactions/index.test.tsx, src/screens/blocks/components/desktop/__snapshots__/index.test.tsx.snap, src/screens/blocks/components/desktop/index.tsx, src/screens/blocks/components/desktop/utils.ts, src/screens/blocks/components/mobile/__snapshots__/index.test.tsx.snap, src/screens/blocks/components/mobile/index.tsx, src/screens/home/components/blocks/components/mobile/__snapshots__/index.test.tsx.snap, src/screens/home/components/blocks/components/mobile/index.tsx, src/screens/token_details/components/transactions/__snapshots__/index.test.tsx.snap, src/screens/token_details/components/transactions/index.test.tsx, src/screens/validator_details/components/transactions/__snapshots__/index.test.tsx.snap, src/screens/validator_details/components/transactions/index.test.tsx
=> update: leader to proposer

CHANGELOG.md, public/locales/en/tokens.json, src/screens/tokens/__snapshots__/index.test.tsx.snap, src/screens/tokens/components/list/__snapshots__/index.test.tsx.snap, src/screens/tokens/components/list/index.test.tsx, src/screens/tokens/components/list/index.tsx, src/screens/tokens/hooks.tsx, src/screens/tokens/index.tsx, src/screens/validators/components/list/index.tsx
=> add: searchbar feature

src/graphql/block_details.graphql, src/graphql/market_data.graphql, src/graphql/types.tsx, src/screens/block_details/__snapshots__/index.test.tsx.snap, src/screens/block_details/hooks.tsx, src/screens/block_details/index.test.tsx
=> add: numTxs

CHANGELOG.md, src/graphql/blocks.graphql, src/graphql/desmos_profile.ts, src/graphql/market_data.graphql, src/graphql/types.tsx
=> update market_data.gql/inflationRate to actions_inflation_rate

package-lock.json, package.json
=> update: dependencies

src/configs/chain_config.mainnet.json, src/configs/chain_config.testnet.json, src/graphql/desmos_profile.ts, src/graphql/types.tsx, src/graphql/validators_address_list.graphql, src/recoil/validators/hooks.ts
=> udpate validator hooks

src/graphql/blocks.graphql, src/graphql/types.tsx, src/screens/home/components/blocks/components/desktop/index.test.tsx, src/screens/home/components/blocks/components/desktop/index.tsx, src/screens/home/components/blocks/components/mobile/index.test.tsx, src/screens/home/components/blocks/components/mobile/index.tsx, src/screens/home/components/blocks/hooks.tsx, src/screens/home/components/blocks/index.test.tsx, src/screens/home/components/blocks/index.tsx, src/screens/home/components/blocks/types.ts
=> revert: home blocks to use profiles

src/screens/blocks/__snapshots__/index.test.tsx.snap, src/screens/blocks/components/desktop/__snapshots__/index.test.tsx.snap, src/screens/blocks/components/desktop/index.tsx, src/screens/blocks/components/desktop/utils.ts, src/screens/blocks/hooks.tsx, src/screens/blocks/index.test.tsx, src/screens/blocks/index.tsx, src/screens/blocks/types.ts
=> enable: blocks test

src/graphql/blocks.graphql, src/graphql/types.tsx, src/screens/blocks/hooks.tsx, src/screens/blocks/index.test.tsx, src/screens/blocks/index.tsx, src/screens/blocks/types.ts
=> remove: blocks aggregation

src/graphql/blocks.graphql, src/graphql/types.tsx, src/screens/blocks/__snapshots__/index.test.tsx.snap, src/screens/blocks/components/desktop/__snapshots__/index.test.tsx.snap, src/screens/blocks/components/desktop/index.tsx, src/screens/blocks/components/desktop/utils.ts, src/screens/blocks/hooks.tsx, src/screens/blocks/index.test.tsx, src/screens/blocks/index.tsx, src/screens/blocks/types.ts, src/screens/home/components/blocks/components/desktop/index.test.tsx, src/screens/home/components/blocks/components/desktop/index.tsx, src/screens/home/components/blocks/components/mobile/index.test.tsx, src/screens/home/components/blocks/components/mobile/index.tsx, src/screens/home/components/blocks/hooks.tsx, src/screens/home/components/blocks/index.test.tsx, src/screens/home/components/blocks/index.tsx, src/screens/home/components/blocks/types.ts
=> 72/fix blocks query UI

CHANGELOG.md, src/screens/validators/components/list/__snapshots__/index.test.tsx.snap, src/screens/validators/components/list/components/tabs/__snapshots__/index.test.tsx.snap, src/screens/validators/components/list/components/tabs/index.test.tsx, src/screens/validators/components/list/components/tabs/index.tsx, src/screens/validators/components/list/index.tsx
=> pass validators count value from parent to child layer & render on ui

src/screens/transactions/index.tsx
=>  reviewed: tx lists

src/components/box/styles.tsx
=> fix: homepage box overflow

src/components/nav/components/desktop/components/action_bar/components/setting_list/index.tsx
=> removed: tx global setting

src/configs/general_config.json
so users can report issues in correct repo. 
closes #98
=> fix config github report address for error page redirect

src/graphql/block_details.graphql, src/graphql/tokens.graphql, src/graphql/transaction_details.graphql, src/graphql/transactions.graphql, src/graphql/types.tsx
=> update: graphql

src/screens/transaction_details/components/overview/index.tsx
=> remove unused part in tx_details overview

src/screens/tokens/components/list/components/desktop/styles.ts
=> BDU-54 fix: token list sorting pointer

src/screens/tokens/__snapshots__/index.test.tsx.snap, src/screens/tokens/components/list/components/desktop/__snapshots__/index.test.tsx.snap, src/screens/tokens/components/list/components/desktop/index.test.tsx, src/screens/tokens/components/list/components/desktop/index.tsx, src/screens/tokens/components/list/components/mobile/__snapshots__/index.test.tsx.snap, src/screens/tokens/components/list/components/mobile/index.tsx, src/screens/tokens/hooks.tsx, src/screens/tokens/types.ts
=> update: name to avatarname

src/screens/transactions/__snapshots__/index.test.tsx.snap, src/screens/transactions/hooks.ts, src/screens/transactions/index.tsx, src/screens/transactions/types.ts
=> update: tx list to only show latest 25

src/screens/transactions/__snapshots__/index.test.tsx.snap, src/screens/transactions/components/index.ts, src/screens/transactions/components/transactions_list/components/desktop/index.tsx, src/screens/transactions/components/transactions_list/components/desktop/styles.ts, src/screens/transactions/components/transactions_list/components/desktop/utils.ts, src/screens/transactions/components/transactions_list/components/index.ts, src/screens/transactions/components/transactions_list/components/mobile/index.tsx, src/screens/transactions/components/transactions_list/components/mobile/styles.ts, src/screens/transactions/components/transactions_list/index.tsx, src/screens/transactions/index.test.tsx, src/screens/transactions/index.tsx
=> update: tx list into table instead of window

codegen.yml, src/graphql/block_details.graphql, src/graphql/transaction_details.graphql, src/graphql/transactions.graphql, src/graphql/types.tsx, src/screens/block_details/__snapshots__/index.test.tsx.snap, src/screens/block_details/hooks.tsx, src/screens/block_details/index.test.tsx, src/screens/home/components/transactions/hooks.tsx, src/screens/transaction_details/__snapshots__/index.test.tsx.snap, src/screens/transaction_details/hooks.ts, src/screens/transaction_details/index.test.tsx, src/screens/transactions/__snapshots__/index.test.tsx.snap, src/screens/transactions/hooks.ts, src/screens/transactions/index.test.tsx
=> update: gql

codegen.yml
=> fix: codegen typo

CHANGELOG.md, public/locales/en/transactions.json, src/components/box_details/styles.ts, src/graphql/transaction_details.graphql, src/graphql/types.tsx, src/screens/transaction_details/__snapshots__/index.test.tsx.snap, src/screens/transaction_details/components/index.ts, src/screens/transaction_details/components/logs/__snapshots__/index.test.tsx.snap, src/screens/transaction_details/components/logs/index.test.tsx, src/screens/transaction_details/components/logs/index.tsx, src/screens/transaction_details/components/logs/styles.ts, src/screens/transaction_details/components/logs/utils.ts, src/screens/transaction_details/hooks.ts, src/screens/transaction_details/index.test.tsx, src/screens/transaction_details/index.tsx, src/screens/transaction_details/types.ts
This PR will add the log component to Transaction details
=> Bdu 89/tx details logs

package-lock.json, package.json
=> update: audit

CHANGELOG.md, src/graphql/desmos_profile.ts, src/graphql/tokens.graphql, src/graphql/types.tsx, src/screens/tokens/__snapshots__/index.test.tsx.snap, src/screens/tokens/components/list/__snapshots__/index.test.tsx.snap, src/screens/tokens/components/list/components/desktop/__snapshots__/index.test.tsx.snap, src/screens/tokens/components/list/components/desktop/index.test.tsx, src/screens/tokens/components/list/components/desktop/index.tsx, src/screens/tokens/components/list/components/desktop/utils.ts, src/screens/tokens/components/list/components/mobile/__snapshots__/index.test.tsx.snap, src/screens/tokens/components/list/components/mobile/components/token/__snapshots__/index.test.tsx.snap, src/screens/tokens/components/list/components/mobile/components/token/index.tsx, src/screens/tokens/components/list/components/mobile/index.test.tsx, src/screens/tokens/components/list/components/mobile/index.tsx, src/screens/tokens/components/list/index.test.tsx, src/screens/tokens/hooks.tsx, src/screens/tokens/index.test.tsx, src/screens/tokens/types.ts
=> token-add-volume

src/screens/account_details/components/index.ts, src/screens/account_details/components/mint_account/index.tsx, src/screens/account_details/index.tsx, src/screens/tokens/components/list/components/desktop/index.tsx, src/screens/tokens/components/list/components/mobile/index.tsx, src/utils/go_to_page.ts
=> update: inital account details base

src/screens/home/components/epoch/hooks.tsx
=> fix: epoch number

src/graphql/account_details_documents.ts, src/graphql/types.tsx, src/screens/account_details/components/native_account/index.tsx, src/screens/account_details/components/tokens/components/tokens_list/components/desktop/index.tsx, src/screens/account_details/components/tokens/components/tokens_list/components/mobile/index.tsx, src/screens/account_details/components/tokens/components/tokens_list/index.tsx, src/screens/account_details/components/tokens/hooks.ts, src/screens/account_details/components/tokens/index.tsx, src/screens/account_details/components/tokens/types.ts
This PR adds the token component to the native account page
=> Bdu 183/tokens

public/locales/en/accounts.json, src/graphql/account_details_documents.ts, src/graphql/types.tsx, src/screens/account_details/components/token_details_account/components/overview/index.tsx, src/screens/account_details/components/token_details_account/components/overview/types.ts, src/screens/account_details/components/token_details_account/hooks.tsx, src/screens/account_details/components/token_details_account/index.tsx, src/screens/account_details/components/token_details_account/types.ts, src/screens/account_details/index.tsx
=> Bdu 190/token overview

CHANGELOG.md, public/locales/en/accounts.json, src/graphql/account_details_documents.ts, src/graphql/types.tsx, src/screens/account_details/components/token_details_account/components/overview/index.tsx, src/screens/account_details/components/token_details_account/components/overview/types.ts, src/screens/account_details/components/token_details_account/hooks.tsx, src/screens/account_details/components/token_details_account/index.tsx, src/screens/account_details/components/token_details_account/types.ts, src/screens/account_details/index.tsx
=> Bdu 189/token details account

src/graphql/transaction_by_address_documents.ts, src/graphql/types.tsx, src/screens/account_details/components/transactions/__snapshots__/index.test.tsx.snap, src/screens/account_details/components/transactions/hooks.ts, src/screens/account_details/components/transactions/index.test.tsx
=> update: unblock staging

public/locales/en/accounts.json, src/graphql/account_details_documents.ts, src/graphql/types.tsx, src/screens/account_details/components/native_account/index.tsx, src/screens/account_details/components/native_account/styles.ts, src/screens/account_details/components/nonce_account/index.tsx, src/screens/account_details/components/nonce_account/styles.ts, src/screens/account_details/components/stake_account/index.tsx, src/screens/account_details/components/stake_account/styles.ts, src/screens/account_details/components/token_account/__snapshots__/index.test.tsx.snap, src/screens/account_details/components/token_account/index.tsx, src/screens/account_details/components/token_account/styles.ts, src/screens/account_details/components/token_details_account/index.tsx, src/screens/account_details/components/token_details_account/styles.ts, src/screens/account_details/components/transactions/hooks.ts, src/screens/account_details/components/vote_account/components/index.ts, src/screens/account_details/components/vote_account/components/skip_rate/index.tsx, src/screens/account_details/components/vote_account/components/skip_rate/styles.ts, src/screens/account_details/components/vote_account/hooks.tsx, src/screens/account_details/components/vote_account/index.tsx, src/screens/account_details/components/vote_account/styles.ts, src/screens/account_details/components/vote_account/types.ts, src/screens/account_details/hooks.ts, src/screens/account_details/index.tsx, src/screens/account_details/styles.ts
=> Bdu 248/validator skip rate

public/locales/en/common.json, src/components/nav/components/seach_bar/hooks.tsx
=> update: global search bar

src/screens/account_details/components/native_account/hooks.tsx
=> fix: vote balance display

src/screens/app/components/inner_app/hooks.ts
=> update: error time

src/screens/app/utils.ts
=> wip: testing preview image

src/screens/account_details/components/stake_account/hooks.ts
=> update: stake status
